map $http_x_vd_canary $vd_force_canary {
    default 0;
    "1" 1;
    "true" 1;
    "always" 1;
}

split_clients "${remote_addr}${http_user_agent}" $vd_canary_bucket {
    0% "canary";
    * "stable";
}

map "$vd_force_canary:$vd_canary_bucket" $vd_api_upstream {
    "1:stable" "vd_api_canary";
    "1:canary" "vd_api_canary";
    "0:canary" "vd_api_canary";
    default "vd_api_stable";
}
