#!/usr/bin/env bash
set -euo pipefail

load_env_file() {
  local env_path="${1:-}"
  local caller="${2:-env_loader}"

  if [[ -z "$env_path" ]]; then
    printf '[%s] Env file path is empty, skipping.\n' "$caller" >&2
    return 0
  fi

  if [[ -f "$env_path" ]]; then
    set -a
    # shellcheck disable=SC1090
    source "$env_path"
    set +a
    printf '[%s] Loaded env file: %s\n' "$caller" "$env_path" >&2
    return 0
  fi

  printf '[%s] Env file not found, continuing with current shell env: %s\n' "$caller" "$env_path" >&2
}

load_env_files() {
  local caller="${1:-env_loader}"
  shift || true
  local env_path
  for env_path in "$@"; do
    load_env_file "$env_path" "$caller"
  done
}

snapshot_process_env() {
  local snapshot_path="${1:-}"
  [[ -n "$snapshot_path" ]] || return 1
  python3 - <<'PY' > "$snapshot_path"
import os
import shlex

for key, value in os.environ.items():
    if value == "":
        continue
    print(f"export {key}={shlex.quote(value)}")
PY
}

restore_process_env() {
  local snapshot_path="${1:-}"
  [[ -f "$snapshot_path" ]] || return 0
  # shellcheck disable=SC1090
  source "$snapshot_path"
  rm -f "$snapshot_path"
}

load_env_file_preserve_process_env() {
  local env_path="${1:-}"
  local caller="${2:-env_loader}"
  local shell_snapshot
  shell_snapshot="$(mktemp)"
  snapshot_process_env "$shell_snapshot"
  load_env_file "$env_path" "$caller"
  restore_process_env "$shell_snapshot"
}

get_runtime_resolved_env_path() {
  local root_dir="${1:-}"
  if [[ -z "$root_dir" ]]; then
    return 1
  fi
  printf '%s\n' "$root_dir/.runtime-cache/run/full-stack/resolved.env"
}

read_env_value_from_file() {
  local env_path="${1:-}"
  local key="${2:-}"
  if [[ -z "$env_path" || -z "$key" || ! -f "$env_path" ]]; then
    return 0
  fi

  python3 - "$env_path" "$key" <<'PY'
from pathlib import Path
import shlex
import sys

env_path = Path(sys.argv[1])
target_key = sys.argv[2]

for raw_line in env_path.read_text(encoding="utf-8").splitlines():
    line = raw_line.strip()
    if not line or line.startswith("#"):
        continue
    if line.startswith("export "):
        line = line[len("export "):].strip()
    if "=" not in line:
        continue
    key, value = line.split("=", 1)
    if key.strip() != target_key:
        continue
    token = value.strip()
    try:
        parts = shlex.split(token, posix=True)
        if len(parts) == 1:
            print(parts[0])
            raise SystemExit(0)
    except ValueError:
        pass
    print(token.strip("'\""))
    raise SystemExit(0)
PY
}

write_runtime_resolved_env() {
  local root_dir="${1:-}"
  local caller="${2:-env_loader}"
  shift 2 || true
  if [[ -z "$root_dir" ]]; then
    printf '[%s] root_dir is empty, cannot write resolved env.\n' "$caller" >&2
    return 1
  fi

  local resolved_path
  resolved_path="$(get_runtime_resolved_env_path "$root_dir")" || return 1
  mkdir -p "$(dirname "$resolved_path")"

  {
    printf '# generated by %s at %s\n' "$caller" "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    local pair key value
    for pair in "$@"; do
      [[ "$pair" == *=* ]] || continue
      key="${pair%%=*}"
      value="${pair#*=}"
      printf 'export %s=%q\n' "$key" "$value"
    done
  } > "$resolved_path"

  printf '[%s] Wrote runtime resolved env: %s\n' "$caller" "$resolved_path" >&2
}

resolve_runtime_route_value() {
  local root_dir="${1:-}"
  local key="${2:-}"
  local cli_value="${3:-}"
  local default_value="${4:-}"

  if [[ -n "$cli_value" ]]; then
    printf '%s\n' "$cli_value"
    return 0
  fi

  local resolved_path resolved_value repo_value
  resolved_path="$(get_runtime_resolved_env_path "$root_dir" 2>/dev/null || true)"
  resolved_value="$(read_env_value_from_file "$resolved_path" "$key")"
  if [[ -n "$resolved_value" ]]; then
    printf '%s\n' "$resolved_value"
    return 0
  fi

  repo_value="$(read_env_value_from_file "$root_dir/.env" "$key")"
  if [[ -n "$repo_value" ]]; then
    printf '%s\n' "$repo_value"
    return 0
  fi

  printf '%s\n' "$default_value"
}

normalize_env_profile() {
  local profile="${1:-local}"
  if [[ -z "$profile" ]]; then
    printf 'local\n'
    return 0
  fi
  if [[ "$profile" =~ ^[A-Za-z0-9._-]+$ ]]; then
    printf '%s\n' "$profile"
    return 0
  fi
  printf 'local\n'
}

get_repo_env_files() {
  local root_dir="${1:-}"
  local profile="${2:-${ENV_PROFILE:-local}}"
  profile="$(normalize_env_profile "$profile")"

  if [[ -z "$root_dir" ]]; then
    return 0
  fi

  local core_file="$root_dir/env/core.env"
  local core_example_file="$root_dir/env/core.env.example"
  local profile_file="$root_dir/env/profiles/${profile}.env"
  local repo_env_file="$root_dir/.env"

  if [[ -f "$core_file" ]]; then
    printf '%s\n' "$core_file"
  elif [[ -f "$core_example_file" ]]; then
    printf '%s\n' "$core_example_file"
  fi

  if [[ -f "$profile_file" ]]; then
    printf '%s\n' "$profile_file"
  fi

  if [[ -f "$repo_env_file" ]]; then
    printf '%s\n' "$repo_env_file"
  fi
}

load_repo_env() {
  local root_dir="${1:-}"
  local caller="${2:-env_loader}"
  local requested_profile="${3:-${ENV_PROFILE:-local}}"
  local profile
  profile="$(normalize_env_profile "$requested_profile")"

  if [[ -z "$root_dir" ]]; then
    printf '[%s] root_dir is empty, skipping repo env load.\n' "$caller" >&2
    return 0
  fi

  local shell_snapshot
  shell_snapshot="$(mktemp)"
  snapshot_process_env "$shell_snapshot"

  local -a env_files=()
  local env_file
  while IFS= read -r env_file; do
    [[ -z "$env_file" ]] && continue
    env_files+=("$env_file")
  done < <(get_repo_env_files "$root_dir" "$profile")

  if (( ${#env_files[@]} > 0 )); then
    load_env_files "$caller" "${env_files[@]}"
  else
    printf '[%s] No env files found under %s (profile=%s), using current shell env only.\n' "$caller" "$root_dir" "$profile" >&2
  fi

  # Inherited process environment has the highest priority.
  restore_process_env "$shell_snapshot"

  export ENV_PROFILE="$profile"
}
