#!/usr/bin/env bash
set -euo pipefail

SCRIPT_NAME="init_env_example"
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

OUTPUT_PATH="${OUTPUT_PATH:-$ROOT_DIR/.env.local.example}"
INIT_ENV_FORCE="${INIT_ENV_FORCE:-0}"

STATE_ROOT="${STATE_ROOT:-$HOME/.video-digestor}"
STATE_DIR="${STATE_DIR:-$STATE_ROOT/state}"
WORKSPACE_DIR="${WORKSPACE_DIR:-$STATE_ROOT/workspace}"
ARTIFACT_DIR="${ARTIFACT_DIR:-$STATE_ROOT/artifacts}"

log() {
  printf '[%s] %s\n' "$SCRIPT_NAME" "$*" >&2
}

fail() {
  log "ERROR: $*"
  exit 1
}

is_truthy() {
  local value
  value="$(printf '%s' "${1:-}" | tr '[:upper:]' '[:lower:]')"
  case "$value" in
    1|true|yes|on) return 0 ;;
    *) return 1 ;;
  esac
}

prepare_dirs() {
  mkdir -p "$STATE_DIR" "$WORKSPACE_DIR" "$ARTIFACT_DIR"
  log "Created local directories:"
  log "  - $STATE_DIR"
  log "  - $WORKSPACE_DIR"
  log "  - $ARTIFACT_DIR"
}

write_example_env() {
  if [[ -e "$OUTPUT_PATH" ]] && ! is_truthy "$INIT_ENV_FORCE"; then
    fail "output exists: $OUTPUT_PATH (set INIT_ENV_FORCE=1 to overwrite)"
  fi

  cat >"$OUTPUT_PATH" <<EOF
# Generated by scripts/init_env_example.sh
# Usage:
#   cp .env.local.example .env.local
#   edit secrets, then: source .env.local

# ---------- Core Runtime ----------
export DATABASE_URL='postgresql+psycopg://localhost:5432/video_analysis'
export TEMPORAL_TARGET_HOST='127.0.0.1:7233'
export TEMPORAL_NAMESPACE='default'
export TEMPORAL_TASK_QUEUE='video-analysis-worker'

export SQLITE_PATH='${STATE_DIR}/worker_state.db'
export SQLITE_STATE_PATH='${STATE_DIR}/worker_state.db'
export PIPELINE_WORKSPACE_DIR='${WORKSPACE_DIR}'
export PIPELINE_ARTIFACT_ROOT='${ARTIFACT_DIR}'

# ---------- API / MCP ----------
export VD_API_BASE_URL='http://127.0.0.1:8000'
export VD_API_TIMEOUT_SEC='20'
# export VD_API_KEY='<optional>'

# ---------- Notifications (Resend) ----------
export RESEND_API_KEY='<required-for-send>'
export RESEND_FROM_EMAIL='Video Digestor <noreply@example.com>'
export NOTIFY_TO_EMAIL='you@example.com'

# ---------- Notification toggles ----------
export NOTIFICATION_ENABLED='true'
export NOTIFICATION_DAILY_DIGEST_ENABLED='true'
export NOTIFICATION_DAILY_DIGEST_HOUR_UTC='1'
export NOTIFICATION_FAILURE_ALERT_ENABLED='true'

# ---------- Daily digest script ----------
export DIGEST_CHANNEL='email'
export DIGEST_DRY_RUN='false'
export DIGEST_FORCE='false'
export DIGEST_FALLBACK_ENABLED='1'
# export DIGEST_TO_EMAIL="\$NOTIFY_TO_EMAIL"

# ---------- Failure alerts script ----------
export FAILURE_CHANNEL='email'
export FAILURE_LOOKBACK_HOURS='24'
export FAILURE_LIMIT='20'
export FAILURE_DRY_RUN='false'
export FAILURE_FORCE='false'
export FAILURE_FALLBACK_ENABLED='1'
# export FAILURE_TO_EMAIL="\$NOTIFY_TO_EMAIL"
EOF

  log "Wrote env template: $OUTPUT_PATH"
}

print_next_steps() {
  cat <<EOF
[${SCRIPT_NAME}] Next steps:
[${SCRIPT_NAME}]   1) cp "$OUTPUT_PATH" "$ROOT_DIR/.env.local"
[${SCRIPT_NAME}]   2) edit "$ROOT_DIR/.env.local" and fill RESEND_* values
[${SCRIPT_NAME}]   3) source "$ROOT_DIR/.env.local"
[${SCRIPT_NAME}]   4) run scripts/run_daily_digest.sh or scripts/run_failure_alerts.sh
EOF
}

main() {
  prepare_dirs
  write_example_env
  print_next_steps
}

main "$@"
